cmake_minimum_required(VERSION 3.10)
set(LIBRARY_NAME sgtools)
option(SGTOOLS_INSTALL_LIB "Install tool library" ON)
option(SGTOOLS_INSTALL_TEST_EXE "build tool tests" ON)
project(${LIBRARY_NAME} C)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_INSTALL_MESSAGE LAZY)
if(UNIX OR APPLE)
    list(APPEND COMPILE_OPTIONS -Wall -Wextra -Wdeprecated -Wno-unused-parameter -Wno-sign-compare -Wshadow -Wnull-dereference -Wdouble-promotion -Wformat=2)
endif(UNIX OR APPLE)
add_library(${LIBRARY_NAME} STATIC 
    ./src/tools.c
    ./src/log.c
)
target_include_directories(${LIBRARY_NAME} PUBLIC ./include)
if(SGTOOLS_INSTALL_LIB)
    install(TARGETS ${LIBRARY_NAME} ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
    install(DIRECTORY ./include/ DESTINATION include)
endif()

if(SGTOOLS_INSTALL_TEST_EXE)
    set(EXECUTABLE_NAME ${LIBRARY_NAME}_exe)
    add_executable(${EXECUTABLE_NAME} ./src/test/main.c)
    target_link_libraries(${EXECUTABLE_NAME} ${LIBRARY_NAME})
    target_include_directories(${EXECUTABLE_NAME} PRIVATE ./include)
endif()
